security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: username
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            provider: doctrine
            logout: 
                path: logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER