# Project language
language: php
php:
  - '7.1'
mysql: 
  - '5.7'
# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer update 
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console hautelook:fixtures:load  -n

# Run script
script:
  - ./bin/phpunit 
# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:

