language: php

php:
  - 7.0
  - 7.1

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
before_script:
  - mysql -e 'create database todolist;'
  - composer install -n
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -n

script:
  - /bin/phpunit

