language: php

php:
  - 7.1

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

# Update composer
before-install:
  - composer self-update

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
install:
  - composer update
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console hautelook:fixtures:load -n --env=test

script:
  - ./bin/phpunit
